USER: admin
PASSWORD: 123456

server:
  port: 9000

spring:
  application:
    name: consumer-client-hystrix

eureka:
  client:
    service-url:
      defaultZone: http://${USER}:${PASSWORD}@localhost:10000/eureka/