USER: admin
PASSWORD: 123456

server:
  port: 9100

spring:
  application:
    name: consumer-ribbon-client

eureka:
  client:
    service-url:
      defaultZone: http://${USER}:${PASSWORD}@localhost:10000/eureka/
  instance:
    prefer-ip-address: true #在eureka中显示ip