USER: admin
PASSWORD: 123456

server:
  port: 20001

spring:
  application:
    name: hystrix-turbine

eureka:
  client:
    service-url:
      defaultZone: http://${USER}:${PASSWORD}@localhost:10000/eureka/

turbine:
  #配置要监控的应用集群
  aggregator:
    cluster-config: default
  app-config: consumer-client-hystrix,consumer-client-hystrix2
  cluster-name-expression: "'default'"
