USER: admin
PASSWORD: 123456

server:
  port: 1000

spring:
  application:
    name: api-gateway-zuul
  #当前应用的security配置
  security:
    user:
      name: admin
      password: 123456

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${USER}:${PASSWORD}@localhost:10000/eureka/

zuul:
  #配置路由映射
  routes:
    provider-server: /ps/** #给指定服务provider-server添加映射地址为/ps
  #ignored-services: provider-server #取消zuul代理的服务

#zuul:
#  #配置路由映射路径
#  routes:
#    adcdef: #随便写, 但保证唯一
#      path: /ps/**
#      serviceId: provider-server